### ISSUE TITLE
Coding style guide, darlo y estudiarlo

### ISSUE THREAD

**Issue by m0llysour** [lernerd/dh-examples#7]

**Comment by guiwoda** [comment]
Se ve bien. Fijate que el comentario multilinea en php es:

``` php
/*
 Comment...
 */
```

Y, por otro lado, en la tabla de "array" cambiaría el "Imprimir una clave numérica" e "Imprimir una clave asociativa" por "Imprimir _usando_ una clave..."

**Comment by m0llysour** [comment]
Gracias @guiwoda ! :smile:
